on:
  push:

name: Linter
jobs:
  Golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run Golint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false"
